### ISSUE TITLE
Explore partition strategies in Flink or other data stream engines and use probabilistic data structures to improve it.

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/explore-flink#7]
**References**
 - [A Deep Dive into Rescalable State in Apache Flink](https://flink.apache.org/features/2017/07/04/flink-rescalable-state.html)
 - [FLIP-8: Rescalable Non-Partitioned State](https://cwiki.apache.org/confluence/display/FLINK/FLIP-8%3A+Rescalable+Non-Partitioned+State)
 - [FLIP-63: Rework table partition support](https://cwiki.apache.org/confluence/display/FLINK/FLIP-63%3A+Rework+table+partition+support)
 - [FLIP-67: Global partitions lifecycle](https://cwiki.apache.org/confluence/display/FLINK/FLIP-67%3A+Global+partitions+lifecycle)
 - [FLIP-31: Pluggable Shuffle Service](https://cwiki.apache.org/confluence/display/FLINK/FLIP-31%3A+Pluggable+Shuffle+Service)
 - [FLIP-47: Checkpoints vs. Savepoints](https://cwiki.apache.org/confluence/display/FLINK/FLIP-47%3A+Checkpoints+vs.+Savepoints)
 - [FLIP-56: Dynamic Slot Allocation](https://cwiki.apache.org/confluence/display/FLINK/FLIP-56%3A+Dynamic+Slot+Allocation)
 - [FLINK-10429 Redesign Flink Scheduling, introducing dedicated Scheduler component](https://issues.apache.org/jira/browse/FLINK-10429)
 - [FLINK-1725 New Partitioner for better load balancing for skewed data](https://issues.apache.org/jira/browse/FLINK-1725). This is the Power of both choices paper. Its flink implementation is here: [PartialPartitioner](https://github.com/anisnasir/flink/blob/master/flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/runtime/partitioner/PartialPartitioner.java). The Flink release is placed [here](https://github.com/anisnasir/flink).
 - Implementing [Power of both choices in Flink](https://melmeric.files.wordpress.com/2014/11/the-power-of-both-choices-practical-load-balancing-for-distributed-stream-processing-engines.pdf) and working on another [Flink](https://github.com/felipegutierrez/flink) repository. Discussing is places [here](https://github.com/apache/flink/pull/1069).
 - Explore and study [Key groups](https://flink.apache.org/features/2017/07/04/flink-rescalable-state.html) to implement Power of both choices in Flink.
 - [How is keyed state managed for KeyedBroadcastProcessFunction in Flink?](https://stackoverflow.com/a/54106967/2096986) in stakoverflow gives a good explanation about Key groups in Flink, together with [FLINK-3755 Introduce key groups for key-value state to support dynamic scaling](https://issues.apache.org/jira/browse/FLINK-3755) and this [doc](https://docs.google.com/document/d/1G1OS1z3xEBOrYD4wSu-LuBCyPUWyFd9l3T9WyssQ63w/edit#heading=h.2suhu1fjxmp4).
 - [FLINK-7561 Add support for pre-aggregation in DataStream API](https://issues.apache.org/jira/browse/FLINK-7561)
 - [[FLINK-7561][streaming] Implement PreAggregationOperator #4626](https://github.com/apache/flink/pull/4626/commits/6d48d44e8206d8bcabb0a87cf741aee2722c6366)
 - [Collect Flink metrics using rest API](https://stackoverflow.com/questions/55016972/how-to-get-metrics-of-all-parallelisms-in-flink)
 - [Getting backpressure from sub tasks using rest API](https://ci.apache.org/projects/flink/flink-docs-release-1.9/monitoring/rest_api.html): a good metric to discover if it is happening backpressure in the reducer is `flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage` and only pre-aggregating in milliseconds we can trade throughput against latency. Starting pre-aggregating within 1 millisecond and change to 10 milliseconds makes a big difference. The usage of buffers droped from 100% to 20%. Further changing to 100 milliseconds it dropped to 10%. The difference can be seen in the throughput plot (records per second), which increased. This is why there is a trade-off between latency to process a pre-aggregation and the throughput between operators.
 - [Flink Network Stack Vol. 2: Monitoring, Metrics, and that Backpressure Thing](https://flink.apache.org/2019/07/23/flink-network-stack-2.html)

**Comment by felipegutierrez** [comment]
Error:
```
java.lang.NullPointerException
	at org.apache.flink.runtime.state.heap.StateTable.put(StateTable.java:336)
	at org.apache.flink.runtime.state.heap.StateTable.put(StateTable.java:159)
	at org.apache.flink.runtime.state.heap.HeapValueState.update(HeapValueState.java:90)
	at org.apache.flink.streaming.api.operators.StreamGroupedReduce.processElement(StreamGroupedReduce.java:66)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processElement(StreamOneInputProcessor.java:163)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:149)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:277)
	at org.apache.flink.streaming.runtime.tasks.mailbox.execution.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:147)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:404)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
17:14:30,512 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job WordCountKeyPartitioning strategy[partial] (df226c268162dc45d7fab3ffcea123d1) switched from state RUNNING to FAILING.
java.lang.NullPointerException
	at org.apache.flink.runtime.state.heap.StateTable.put(StateTable.java:336)
	at org.apache.flink.runtime.state.heap.StateTable.put(StateTable.java:159)
	at org.apache.flink.runtime.state.heap.HeapValueState.update(HeapValueState.java:90)
	at org.apache.flink.streaming.api.operators.StreamGroupedReduce.processElement(StreamGroupedReduce.java:66)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processElement(StreamOneInputProcessor.java:163)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:149)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:277)
	at org.apache.flink.streaming.runtime.tasks.mailbox.execution.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:147)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:404)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by felipegutierrez** [comment]
It has to be implemented in Flink core, not on top of Flink
